In [22]:
import time
import pandas as pd
import pymysql
from sqlalchemy import create_engine
import configparser



import pandas as pd
import pymysql


# In[2]:


## 날씨정보
weather = pd.read_csv('./car.csv', encoding = 'cp949')
weather.reset_index(drop = True)

,car_num,distance,distance_cum,speed_av,speed_max,operating_time,stop_num,stop_time,stop_rate,drive_time,rpm_max,rpm_av
0,1111,299,431844,17.82,57,60419,832,19100,31.61,41319,1620,924
1,1112,286,402323,18.26,62,56393,818,17071,30.27,39322,1592,931
2,1113,311,443480,17.96,61,62325,834,18339,29.42,43986,1606,926
3,1114,215,111809,14.08,48,54970,754,16457,29.94,38513,1780,798
4,1115,250,230163,16.17,57,55673,697,16219,29.13,39454,1720,780
...,...,...,...,...,...,...,...,...,...,...,...,...
95,1206,55,577120,14.47,52,13681,204,5009,36.61,8672,1666,851
96,1207,42,577162,19.16,52,7890,106,2025,25.67,5865,1657,912
97,1208,25,531007,20.84,55,4319,49,1002,23.20,3317,1585,948
98,1209,55,531062,16.86,58,11746,186,4085,34.78,7661,1698,869
99,1210,17,2663,10.00,54,6117,100,2664,43.55,3453,2640,1105

In [23]:
# 컬럼 리스트 생성
car_num = weather.iloc[:,0].to_list()
distance = weather.iloc[:,1].to_list()
distance_cum = weather.iloc[:,2].to_list()
speed_av = weather.iloc[:,3].to_list()
speed_max= weather.iloc[:,4].to_list()
operating_time = weather.iloc[:,5].to_list()
stop_num=weather.iloc[:,6].to_list()
stop_time =weather.iloc[:,7].to_list()
stop_rate = weather.iloc[:,8].to_list()
drive_time = weather.iloc[:,9].to_list()
rpm_max = weather.iloc[:,10].to_list()
rpm_av = weather.iloc[:,11].to_list()

# In[4]:


list_sqlData = []
# sql문 생성
for i in range(len(weather)) :
    a = car_num[i], distance[i], distance_cum[i], speed_av[i], speed_max[i], operating_time[i], stop_num[i], stop_time[i], stop_rate[i], drive_time[i],rpm_max[i],rpm_av[i]
    list_sqlData.append(a)

list_sqlData

[(1111, 299, 431844, 17.82, 57, 60419, 832, 19100, 31.61, 41319, 1620, 924),
 (1112, 286, 402323, 18.26, 62, 56393, 818, 17071, 30.27, 39322, 1592, 931),
 (1113, 311, 443480, 17.96, 61, 62325, 834, 18339, 29.42, 43986, 1606, 926),
 (1114, 215, 111809, 14.08, 48, 54970, 754, 16457, 29.94, 38513, 1780, 798),
 (1115, 250, 230163, 16.17, 57, 55673, 697, 16219, 29.13, 39454, 1720, 780),
 (1116, 266, 428920, 16.82, 62, 56933, 713, 15464, 27.16, 41469, 1709, 820),
 (1117, 262, 432548, 16.02, 57, 58880, 662, 16305, 27.69, 42575, 1822, 785),
 (1118, 248, 226343, 16.83, 55, 53056, 711, 13889, 26.18, 39167, 1680, 804),
 (1119, 249, 382584, 16.31, 57, 54976, 685, 15533, 28.25, 39443, 2100, 733),
 (1120, 236, 320108, 15.57, 64, 54584, 809, 15750, 28.85, 38834, 1700, 874),
 (1121, 238, 298114, 16.09, 57, 53264, 831, 13745, 25.81, 39519, 1840, 887),
 (1122, 237, 355274, 15.84, 56, 53855, 860, 14286, 26.53, 39569, 1820, 889),
 (1123, 195, 297215, 16.24, 60, 43230, 620, 11172, 25.84, 32058, 1814, 865),
 (1124, 242, 336170, 15.74, 60, 55353, 858, 16009, 28.92, 39344, 1640, 866),
 (1125, 273, 179103, 16.46, 65, 59714, 887, 17619, 29.51, 42095, 1576, 867),
 (1126, 271, 301322, 14.37, 58, 67910, 915, 22722, 33.46, 45188, 1540, 614),
 (1127, 283, 94255, 16.3, 55, 62492, 887, 19443, 31.11, 43049, 1602, 671),
 (1128, 249, 299496, 13.88, 54, 64597, 864, 24116, 37.33, 40481, 1440, 634),
 (1129, 295, 296636, 17.05, 61, 62283, 872, 18058, 28.99, 44225, 1647, 855),
 (1130, 245, 142107, 15.07, 59, 58518, 909, 16487, 28.17, 42031, 1580, 830),
 (1131, 225, 338686, 14.1, 60, 57458, 741, 19541, 34.01, 37917, 1520, 637),
 (1132, 152, 342573, 13.0, 59, 42103, 545, 16322, 38.77, 25781, 1660, 614),
 (1133, 293, 257954, 16.65, 62, 63341, 933, 21520, 33.97, 41821, 1602, 908),
 (1134, 226, 143905, 15.25, 57, 53354, 822, 16678, 31.26, 36676, 1651, 842),
 (1135, 225, 343240, 13.86, 56, 58435, 746, 19050, 32.6, 39385, 1400, 624),
 (1136, 226, 338123, 13.49, 56, 60290, 825, 21280, 35.3, 39010, 1380, 593),
 (1137, 289, 119460, 16.42, 57, 63363, 850, 20079, 31.69, 43284, 1369, 646),
 (1138, 289, 121104, 16.42, 59, 63363, 866, 19863, 31.35, 43500, 2399, 702),
 (1139, 225, 9747, 14.78, 60, 54801, 849, 16101, 29.38, 38700, 1618, 654),
 (1140, 225, 11296, 14.97, 56, 54121, 860, 16468, 30.43, 37653, 1393, 643),
 (1141, 220, 46377, 14.68, 55, 53962, 839, 15232, 28.23, 38730, 1399, 654),
 (1142, 226, 4263, 15.11, 55, 53835, 842, 16313, 30.3, 37522, 2383, 657),
 (1143, 215, 48972, 15.4, 58, 50245, 703, 12970, 25.81, 37275, 1580, 681),
 (1144, 231, 304649, 13.45, 56, 61851, 780, 21822, 35.28, 40029, 1320, 581),
 (1145, 187, 123620, 16.67, 58, 40377, 566, 14296, 35.41, 26081, 1855, 813),
 (1146, 225, 43089, 15.05, 54, 53814, 784, 14198, 26.38, 39616, 1518, 657),
 (1147, 243, 54007, 15.93, 55, 54928, 692, 15226, 27.72, 39702, 1463, 636),
 (1148, 310, 51368, 17.62, 61, 63355, 840, 18406, 29.05, 44949, 1780, 923),
 (1149, 310, 445963, 18.21, 59, 61299, 784, 16298, 26.59, 45001, 1640, 932),
 (1150, 248, 481734, 15.85, 59, 56343, 744, 16231, 28.81, 40112, 1560, 772),
 (1151, 149, 231924, 15.96, 61, 33607, 425, 9735, 28.97, 23872, 1795, 674),
 (1152, 242, 47898, 16.18, 54, 53846, 683, 14615, 27.14, 39231, 1325, 637),
 (1153, 252, 435150, 16.28, 56, 55738, 707, 16211, 29.08, 39527, 1680, 769),
 (1154, 51, 10468, 16.61, 49, 11053, 134, 2583, 23.37, 8470, 1486, 676),
 (1155, 254, 68365, 16.16, 60, 56592, 699, 16067, 28.39, 40525, 1800, 778),
 (1156, 295, 1785, 16.62, 57, 63883, 880, 20145, 31.53, 43738, 1448, 660),
 (1157, 248, 4420, 16.65, 54, 53632, 701, 13873, 25.87, 39759, 1432, 625),
 (1158, 248, 4573, 16.82, 57, 53067, 647, 15165, 28.58, 37902, 1540, 700),
 (1159, 251, 175005, 16.49, 58, 54800, 678, 15516, 28.31, 39284, 1760, 757),
 (1160, 52, 10450, 16.44, 52, 11385, 129, 3187, 27.99, 8198, 1638, 678),
 (1161, 255, 1413, 16.11, 60, 56987, 777, 20687, 36.3, 36300, 1632, 655),
 (1162, 296, 1663, 16.86, 56, 63201, 902, 19829, 31.37, 43372, 1629, 637),
 (1163, 245, 193296, 16.41, 58, 53763, 747, 18670, 34.73, 35093, 2121, 693),
 (1164, 237, 318767, 15.86, 62, 53803, 896, 14643, 27.22, 39160, 1720, 871),
 (1165, 179, 340557, 13.35, 57, 48282, 647, 19373, 40.12, 28909, 1560, 754),
 (1166, 305, 52724, 17.99, 63, 61036, 854, 17670, 28.95, 43366, 1680, 928),
 (1167, 310, 432980, 17.92, 65, 62261, 854, 18256, 29.32, 44005, 1700, 924),
 (1168, 213, 441457, 17.41, 61, 44038, 604, 13342, 30.3, 30696, 1800, 924),
 (1169, 248, 4839, 16.05, 60, 55641, 758, 18088, 32.51, 37553, 1594, 683),
 (1170, 278, 96086, 16.53, 57, 60561, 820, 17288, 28.55, 43273, 1282, 638),
 (1171, 283, 1850, 16.6, 58, 61362, 867, 19628, 31.99, 41734, 1368, 651),
 (1172, 279, 95204, 16.58, 57, 60567, 867, 19375, 31.99, 41192, 1577, 677),
 (1173, 282, 84020, 16.23, 56, 62564, 897, 19846, 31.72, 42718, 1738, 738),
 (1174, 167, 189592, 16.15, 56, 37220, 504, 12892, 34.64, 24328, 1434, 668),
 (1175, 300, 69529, 17.75, 62, 60857, 813, 18853, 30.98, 42004, 1600, 924),
 (1176, 238, 21412, 15.94, 61, 53737, 797, 15487, 28.82, 38250, 1580, 877),
 (1177, 51, 189891, 14.8, 54, 12407, 169, 4098, 33.03, 8309, 1593, 644),
 (1178, 51, 172302, 15.73, 59, 11672, 151, 3821, 32.74, 7851, 1401, 634),
 (1179, 252, 442215, 16.33, 61, 55553, 712, 15050, 27.09, 40503, 1640, 747),
 (1180, 77, 25945, 14.06, 55, 19718, 304, 6163, 31.26, 13555, 1770, 854),
 (1181, 226, 334315, 14.85, 60, 54785, 918, 15013, 27.4, 39772, 2162, 860),
 (1182, 238, 4840, 16.58, 60, 51680, 696, 16980, 32.86, 34700, 1556, 840),
 (1183, 240, 445095, 16.47, 60, 52472, 739, 18515, 35.29, 33957, 1660, 911),
 (1184, 45, 412840, 15.77, 62, 10270, 167, 3743, 36.45, 6527, 1760, 857),
 (1185, 45, 412885, 13.91, 55, 11647, 208, 4445, 38.16, 7202, 1812, 833),
 (1186, 45, 412930, 15.53, 48, 10430, 178, 3365, 32.26, 7065, 1582, 865),
 (1187, 20, 412950, 16.49, 55, 4366, 82, 1266, 29.0, 3100, 1468, 871),
 (1188, 45, 1016825, 16.17, 61, 10021, 147, 3235, 32.28, 6786, 1800, 963),
 (1189, 45, 1016871, 13.3, 65, 12185, 204, 4577, 37.56, 7608, 1900, 865),
 (1190, 46, 1016917, 13.96, 62, 11860, 204, 4642, 39.14, 7218, 1740, 875),
 (1191, 45, 1016962, 13.64, 56, 11876, 212, 4323, 36.4, 7553, 1640, 871),
 (1192, 45, 1017007, 14.52, 55, 11154, 189, 3915, 35.1, 7239, 1640, 888),
 (1193, 43, 20074, 14.13, 60, 10956, 187, 4763, 43.47, 6193, 1661, 623),
 (1194, 44, 20119, 12.91, 58, 12271, 216, 5685, 46.33, 6586, 1981, 678),
 (1195, 44, 20163, 13.65, 54, 11604, 200, 4857, 41.86, 6747, 1694, 667),
 (1196, 22, 542233, 16.88, 51, 4693, 62, 1442, 30.73, 3251, 1260, 718),
 (1197, 44, 542277, 13.87, 51, 11418, 210, 4455, 39.02, 6963, 1500, 732),
 (1198, 44, 542321, 14.93, 55, 10609, 194, 3901, 36.77, 6708, 1560, 742),
 (1199, 43, 542364, 13.02, 53, 11888, 190, 4489, 37.76, 7399, 1440, 690),
 (1200, 44, 542408, 14.06, 53, 11262, 176, 3642, 32.34, 7620, 1340, 685),
 (1201, 24, 542432, 14.8, 49, 5838, 77, 1959, 33.56, 3879, 1260, 682),
 (1202, 22, 576901, 20.71, 57, 3824, 41, 1023, 26.75, 2801, 1760, 926),
 (1203, 55, 576956, 17.08, 61, 11593, 161, 4113, 35.48, 7480, 1680, 870),
 (1204, 55, 577011, 17.24, 61, 11487, 155, 3644, 31.72, 7843, 1738, 881),
 (1205, 54, 577065, 17.35, 53, 11204, 186, 3519, 31.41, 7685, 1674, 889),
 (1206, 55, 577120, 14.47, 52, 13681, 204, 5009, 36.61, 8672, 1666, 851),
 (1207, 42, 577162, 19.16, 52, 7890, 106, 2025, 25.67, 5865, 1657, 912),
 (1208, 25, 531007, 20.84, 55, 4319, 49, 1002, 23.2, 3317, 1585, 948),
 (1209, 55, 531062, 16.86, 58, 11746, 186, 4085, 34.78, 7661, 1698, 869),
 (1210, 17, 2663, 10.0, 54, 6117, 100, 2664, 43.55, 3453, 2640, 1105)]